# -*- coding: utf-8 -*-
"""FlashVocab.ver1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7l3iI01hJw5gaxg9xEit8x7lJZJQXT1
"""



import gradio as gr
import random
import pandas as pd # ランキング表示にpandasを使用
import json # ランキングデータの永続化に使用
import os # ファイルの存在確認に使用

# 単語データ（チャプター別に分類）
word_dict_by_chapter = {
    1: { "appear": "現れる", "arrive": "到着する", "believe": "信じる", "build": "建てる", "carry": "運ぶ", "change": "変える", "choose": "選ぶ", "decide": "決める", "enjoy": "楽しむ", "explain": "説明する", "feel": "感じる", "finish": "終える", "follow": "従う", "hope": "願う", "invite": "招待する", "join": "参加する", "keep": "保つ", "lose": "失う", "meet": "会う", "move": "動かす", "open": "開ける", "plan": "計画する", "receive": "受け取る", "remember": "覚えている", "send": "送る", "share": "共有する", "study": "勉強する", "suggest": "提案する", "travel": "旅行する", "visit": "訪れる" },
    2: { "banana": "バナナ", "orange": "オレンジ", "grape": "ぶどう" },
    3: { "cherry": "さくらんぼ", "strawberry": "いちご", "blueberry": "ブルーベリー" },
    4: { "computer": "コンピュータ", "keyboard": "キーボード", "mouse": "マウス" },
    5: { "algorithm": "アルゴリズム", "dataframe": "データフレーム", "neural network": "ニューラルネットワーク" }
}

# グローバルな状態変数 (GradioのStateはリストで保持すると内部で変更可能)
current_word = [""]
current_chapter = [1] # デフォルトのチャプター
shuffled_word_queues = {} # 各チャプターに対応する出題待ちの単語リストを管理
score = [0]
question_number = [0] # 10問で区切るための出題数カウンタ

LEADERBOARD_FILE = 'leaderboard.json'
leaderboard = [] # ランキングデータを保存するリスト: [{'name': 'Player1', 'score': 8}, ...]

def save_leaderboard():
    """リーダーボードデータをファイルに保存する"""
    with open(LEADERBOARD_FILE, 'w', encoding='utf-8') as f:
        json.dump(leaderboard, f, ensure_ascii=False, indent=4)

def load_leaderboard():
    """ファイルからリーダーボードデータを読み込む"""
    if os.path.exists(LEADERBOARD_FILE):
        with open(LEADERBOARD_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []

# アプリケーション起動時にリーダーボードをロード
leaderboard = load_leaderboard()

def get_shuffled_words_for_chapter(chapter):
    """指定されたチャプターの単語リストをシャッフルして返す"""
    words = list(word_dict_by_chapter.get(chapter, {}).keys())
    random.shuffle(words)
    return words

def get_next_word_and_reset_if_needed(chapter_input):
    """次の単語を取得し、ゲーム終了時やチャプター変更時にスコアと出題数をリセットする"""
    selected_chapter = int(chapter_input)

    # ゲームが終了している場合、またはチャプターが変更された場合、スコアと出題数をリセット
    if question_number[0] >= 10 or selected_chapter != current_chapter[0]:
        score[0] = 0
        question_number[0] = 0
        # 新しいゲームのために、現在のチャプターの単語キューを再シャッフル
        shuffled_word_queues[selected_chapter] = get_shuffled_words_for_chapter(selected_chapter)

    current_chapter[0] = selected_chapter # 現在のチャプターを更新

    # 現在のチャプターの単語キューが空の場合、またはまだ初期化されていない場合
    if not shuffled_word_queues.get(selected_chapter) or len(shuffled_word_queues[selected_chapter]) == 0:
        shuffled_word_queues[selected_chapter] = get_shuffled_words_for_chapter(selected_chapter)

    words_queue = shuffled_word_queues[selected_chapter]

    if not words_queue: # 万が一単語データがない場合のエラーハンドリング
        return "チャプターエラー", "", "エラー: このチャプターの単語がありません。", 0, 0, "", \
               gr.update(interactive=False), gr.update(interactive=False), gr.update(interactive=False), gr.update(visible=False), gr.update(visible=False)

    current_word[0] = words_queue.pop(0) # キューから次の単語を取り出す

    # 結果メッセージと最終スコアメッセージはクリアし、ボタンは初期状態（有効）に設定
    return current_word[0], "", "", score[0], question_number[0], "", \
           gr.update(interactive=True), gr.update(interactive=True), gr.update(interactive=False), gr.update(visible=False), gr.update(visible=False)

def display_leaderboard():
    """リーダーボードをDataFrameで表示用に整形して返す"""
    if not leaderboard:
        return pd.DataFrame({'名前': [], 'スコア': []})

    # スコアで降順にソート
    sorted_leaderboard = sorted(leaderboard, key=lambda x: x['score'], reverse=True)
    df = pd.DataFrame(sorted_leaderboard)
    df.columns = ['名前', 'スコア'] # 日本語の列名に設定
    return df

def process_answer(user_answer):
    """ユーザーの回答をチェックし、スコアを更新する"""
    correct_answer = word_dict_by_chapter.get(current_chapter[0], {}).get(current_word[0], "")
    is_correct = (user_answer.strip().lower() == correct_answer.lower())

    if is_correct:
        score[0] += 1

    question_number[0] += 1

    feedback_msg = "⭕️ 正解！" if is_correct else f"❌ 不正解... 正解は「{correct_answer}」です。"
    final_message_text = ""

    # Always update leaderboard display (even if no new score is added yet)
    updated_leaderboard_df = display_leaderboard()

    if question_number[0] >= 10:
        final_message_text = f"10問終了！最終スコアは {score[0]} / 10 です。\n名前を入力して「スコアを登録」ボタンでランキングに記録してください。"
        # 10問終了後は、回答と次の問題ボタンを無効化し、リセットボタンを有効化
        return feedback_msg, score[0], question_number[0], final_message_text, \
               gr.update(interactive=False), gr.update(interactive=False), gr.update(interactive=True), \
               gr.update(visible=True, value=""), gr.update(visible=True), updated_leaderboard_df # player_name_input, submit_score_button visible
    else:
        # 10問未満の場合は、回答と次の問題ボタンを有効化し、リセットボタンは無効のまま
        return feedback_msg, score[0], question_number[0], final_message_text, \
               gr.update(interactive=True), gr.update(interactive=True), gr.update(interactive=False), \
               gr.update(visible=False), gr.update(visible=False), updated_leaderboard_df # player_name_input, submit_score_button hidden

def submit_final_score(player_name):
    """ユーザーが名前を入力してスコアをランキングに登録する"""
    if not player_name or player_name.strip() == "":
        # If no name is entered, keep them visible and prompt again, don't update leaderboard_display yet
        return gr.update(visible=True), gr.update(visible=True), display_leaderboard(), "名前を入力してください！"
    else:
        leaderboard.append({'name': player_name.strip(), 'score': score[0]})
        save_leaderboard() # スコアを保存
        updated_leaderboard_df = display_leaderboard()
        # Hide name input and submit button after successful submission, clear name
        return gr.update(value="", visible=False), gr.update(visible=False), updated_leaderboard_df, f"ランキングに {player_name.strip()} さんのスコア {score[0]} が記録されました！"

def reset_game_manually(chapter_input):
    """ゲームの状態を手動でリセットし、新しいゲームを開始する"""
    score[0] = 0
    question_number[0] = 0
    selected_chapter = int(chapter_input)
    current_chapter[0] = selected_chapter # 現在のチャプターを更新

    # 現在のチャプターの単語キューを強制的に再シャッフル
    shuffled_word_queues[selected_chapter] = get_shuffled_words_for_chapter(selected_chapter)

    words_queue = shuffled_word_queues[selected_chapter]
    if not words_queue: # 万が一単語データがない場合のエラーハンドリング
        return "チャプターエラー", "", "エラー: このチャプターの単語がありません。", 0, 0, "", \
               gr.update(interactive=False), gr.update(interactive=False), gr.update(interactive=False), gr.update(visible=False), gr.update(visible=False)

    current_word[0] = words_queue.pop(0) # 最初の単語を取得

    # 全てのUI要素を初期状態に戻す
    return current_word[0], "", "", 0, 0, "", \
           gr.update(interactive=True), gr.update(interactive=True), gr.update(interactive=False), \
           gr.update(visible=False), gr.update(visible=False)

with gr.Blocks() as demo:
    gr.Markdown("# 🧠 爆速単語記憶アプリ")

    gr.Markdown("## チャプター選択")
    chapter_selector = gr.Radio(
        choices=[1, 2, 3, 4, 5],
        value=1,
        label="チャプター",
        interactive=True
    )

    with gr.Row():
        word_display = gr.Textbox(label="問題（英語）", interactive=False)
        answer_input = gr.Textbox(label="あなたの答え（日本語）")

    result_output = gr.Label(label="結果")

    final_score_msg = gr.Markdown("") # 最終スコアメッセージ表示用

    with gr.Row():
        score_output = gr.Label(label="正解数", value=0)
        question_number_output = gr.Label(label="出題数", value=0)

    gr.Markdown("### ランキングを記録")
    player_name_input = gr.Textbox(label="あなたの名前", placeholder="名前を入力してください", visible=False)
    submit_score_button = gr.Button("スコアを登録", visible=False) # 10問終了時に表示

    gr.Markdown("### ランキング")
    leaderboard_display = gr.DataFrame(headers=["名前", "スコア"], row_count=5, col_count=2, interactive=False)

    with gr.Row():
        btn_next = gr.Button("次の問題")
        btn_submit = gr.Button("回答する")
        btn_reset = gr.Button("ゲームをリセット", interactive=False) # 初期状態では無効

    # 回答ボタンのクリックイベント
    btn_submit.click(
        process_answer,
        inputs=[answer_input],
        outputs=[result_output, score_output, question_number_output, final_score_msg, btn_submit, btn_next, btn_reset, player_name_input, submit_score_button, leaderboard_display]
    )

    # スコア登録ボタンのクリックイベント
    submit_score_button.click(
        submit_final_score,
        inputs=[player_name_input],
        outputs=[player_name_input, submit_score_button, leaderboard_display, final_score_msg]
    )

    # 次の問題ボタンのクリックイベント
    btn_next.click(
        get_next_word_and_reset_if_needed,
        inputs=[chapter_selector],
        outputs=[word_display, answer_input, result_output, score_output, question_number_output, final_score_msg, btn_submit, btn_next, btn_reset, player_name_input, submit_score_button]
    )

    # リセットボタンのクリックイベント
    btn_reset.click(
        reset_game_manually,
        inputs=[chapter_selector],
        outputs=[word_display, answer_input, result_output, score_output, question_number_output, final_score_msg, btn_submit, btn_next, btn_reset, player_name_input, submit_score_button]
    )

    # アプリの初期ロード時に最初の問題を表示とリーダーボードの表示
    demo.load(
        lambda x: get_next_word_and_reset_if_needed(x) + (display_leaderboard(),),
        inputs=[chapter_selector],
        outputs=[word_display, answer_input, result_output, score_output, question_number_output, final_score_msg, btn_submit, btn_next, btn_reset, player_name_input, submit_score_button, leaderboard_display]
    )

# share=True にすると、スマホなど他の端末からもアクセスできるURLが発行されます
demo.launch(

    server_name="0.0.0.0",

    server_port=int(os.environ.get("PORT", 7860))

)